/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/catalog/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Status */
        get: operations["catalog_status_v1_catalog_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Elections */
        get: operations["elections_v1_elections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Election Detail */
        get: operations["election_detail_v1_elections__election_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backtests */
        get: operations["backtests_v1_elections__election_id__backtests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/coalitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coalitions */
        get: operations["coalitions_v1_elections__election_id__coalitions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drivers */
        get: operations["drivers_v1_elections__election_id__drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_v1_elections__election_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/forecast/alternatives/{model_family}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alternative Forecast */
        get: operations["alternative_forecast_v1_elections__election_id__forecast_alternatives__model_family__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast History */
        get: operations["forecast_history_v1_elections__election_id__forecasts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/map-layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Map Layers */
        get: operations["map_layers_v1_elections__election_id__map_layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/mechanics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mechanics */
        get: operations["mechanics_v1_elections__election_id__mechanics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/model-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model Comparison */
        get: operations["model_comparison_v1_elections__election_id__model_comparison_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/official-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Official Results */
        get: operations["official_results_v1_elections__election_id__official_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Simulation Summary */
        get: operations["simulation_summary_v1_elections__election_id__simulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/elections/{election_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_v1_elections__election_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forecast-snapshots/{snapshot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast Snapshot */
        get: operations["forecast_snapshot_v1_forecast_snapshots__snapshot_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jurisdictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jurisdictions */
        get: operations["jurisdictions_v1_jurisdictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_v1_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestMetrics */
        BacktestMetrics: {
            /** Brier Ci High */
            brier_ci_high: number;
            /** Brier Ci Low */
            brier_ci_low: number;
            /** Brier Score */
            brier_score: number;
            /** Calibration Error */
            calibration_error: number;
            /** Folds */
            folds: number;
            /** Interval Coverage */
            interval_coverage: number;
            /** Model Family */
            model_family: string;
            /** Vote Share Rmse */
            vote_share_rmse: number;
        };
        /** CatalogStatus */
        CatalogStatus: {
            /** Calendar Only */
            calendar_only: number;
            /** Eligibility Rule */
            eligibility_rule: string;
            /** Eligibility Snapshot Sha256 */
            eligibility_snapshot_sha256: string;
            /** Eligibility Version */
            eligibility_version: number;
            /** Eligibility Year */
            eligibility_year: number;
            /** Eligible Jurisdictions */
            eligible_jurisdictions: number;
            /** Forecast Ready */
            forecast_ready: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Mechanics Blocked */
            mechanics_blocked: number;
            /** Schema Version */
            schema_version: number;
            /** Sourced Calendars */
            sourced_calendars: number;
            /** Total Jurisdictions */
            total_jurisdictions: number;
        };
        /** CoalitionForecast */
        CoalitionForecast: {
            /** Majority Probability */
            majority_probability: number;
            /** Member Ids */
            member_ids: string[];
            /** Seats High */
            seats_high: number;
            /** Seats Low */
            seats_low: number;
            /** Seats Median */
            seats_median: number;
        };
        /** CoalitionReport */
        CoalitionReport: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Coalitions */
            coalitions: components["schemas"]["CoalitionForecast"][];
            data_quality: components["schemas"]["QualityGrade"];
            /** Election Id */
            election_id: string;
            /** Freshness */
            freshness: string;
            /** Majority */
            majority: number;
            /** Model Version */
            model_version: string;
            /** Provenance */
            provenance: components["schemas"]["SourceRef"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** Contestant */
        Contestant: {
            /** Color */
            color: string;
            /** Id */
            id: string;
            /** Ideology */
            ideology?: string | null;
            /**
             * Incumbent
             * @default false
             */
            incumbent: boolean;
            /** Leader */
            leader?: string | null;
            /** Name */
            name: string;
            /** Short Name */
            short_name: string;
        };
        /** ContestantForecast */
        ContestantForecast: {
            /** Contestant Id */
            contestant_id: string;
            /** Projected Seats */
            projected_seats?: number | null;
            /** Projected Share */
            projected_share: number;
            /** Seats High */
            seats_high?: number | null;
            /** Seats Low */
            seats_low?: number | null;
            /** Share High */
            share_high: number;
            /** Share Low */
            share_low: number;
            /** Win Probability */
            win_probability: number;
        };
        /**
         * CoverageStatus
         * @enum {string}
         */
        CoverageStatus: "forecast" | "calendar_only" | "mechanics_blocked";
        /** DriverContribution */
        DriverContribution: {
            /** Confidence */
            confidence: number;
            /** Contribution */
            contribution: number;
            /** Direction */
            direction: string;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** DriverReport */
        DriverReport: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            data_quality: components["schemas"]["QualityGrade"];
            /** Drivers */
            drivers: components["schemas"]["DriverContribution"][];
            /** Election Id */
            election_id: string;
            /** Freshness */
            freshness: string;
            /** Model Version */
            model_version: string;
            /** Provenance */
            provenance: components["schemas"]["SourceRef"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Sensitivity */
            sensitivity?: components["schemas"]["DriverSensitivity"][];
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** DriverSensitivity */
        DriverSensitivity: {
            /** Clipped */
            clipped: boolean;
            /** Confidence */
            confidence: number;
            /** Driver Key */
            driver_key: string;
            /** Label */
            label: string;
            /**
             * Method
             * @default One-at-a-time structural perturbation; all other inputs held constant
             */
            method: string;
            /** Negative Incumbent Share Shift */
            negative_incumbent_share_shift: number;
            /**
             * Negative Scenario
             * @default -1
             */
            negative_scenario: number;
            /** Observed Incumbent Share Shift */
            observed_incumbent_share_shift: number;
            /** Observed Scenario */
            observed_scenario: number;
            /** Positive Incumbent Share Shift */
            positive_incumbent_share_shift: number;
            /**
             * Positive Scenario
             * @default 1
             */
            positive_scenario: number;
        };
        /** Election */
        Election: {
            /** Contestants */
            contestants: components["schemas"]["Contestant"][];
            /** Date Confidence */
            date_confidence: string;
            /** Election Date */
            election_date: string | null;
            /** Id */
            id: string;
            /** Jurisdiction Id */
            jurisdiction_id: string;
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
            /** Majority */
            majority?: number | null;
            /** Name */
            name: string;
            /** Seats Total */
            seats_total?: number | null;
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
            /** Status */
            status: string;
            system: components["schemas"]["ElectionSystem"];
            /**
             * Threshold
             * @default 0
             */
            threshold: number;
        };
        /** ElectionDetail */
        ElectionDetail: {
            election: components["schemas"]["Election"];
            forecast: components["schemas"]["ForecastSnapshot"] | null;
            jurisdiction: components["schemas"]["Jurisdiction"];
        };
        /** ElectionMechanics */
        ElectionMechanics: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            data_quality: components["schemas"]["QualityGrade"];
            /** Election Id */
            election_id: string;
            /** Forecast Enabled */
            forecast_enabled: boolean;
            /** Freshness */
            freshness: string;
            /** Model Version */
            model_version: string;
            /** Provenance */
            provenance: components["schemas"]["SourceRef"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Rules */
            rules: {
                [key: string]: unknown;
            };
            /** Source Adapters */
            source_adapters: {
                [key: string]: unknown;
            }[];
            system: components["schemas"]["ElectionSystem"];
        };
        /**
         * ElectionSystem
         * @enum {string}
         */
        ElectionSystem: "unresolved" | "presidential_runoff" | "fptp" | "proportional" | "mixed_member" | "electoral_college" | "institutional";
        /** ForecastSnapshot */
        ForecastSnapshot: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Coalition Outcomes */
            coalition_outcomes: components["schemas"]["CoalitionForecast"][];
            data_quality: components["schemas"]["QualityGrade"];
            /** Driver Sensitivity */
            driver_sensitivity?: components["schemas"]["DriverSensitivity"][];
            /** Drivers */
            drivers: components["schemas"]["DriverContribution"][];
            /** Election Id */
            election_id: string;
            /** Freshness */
            freshness: string;
            /** Headline */
            headline: string;
            /** Id */
            id: string;
            /** Input Provenance */
            input_provenance: components["schemas"]["SourceRef"][];
            /** Input Revision Ids */
            input_revision_ids?: string[];
            /** Majority Probability */
            majority_probability: number;
            /** Methodology Url */
            methodology_url: string;
            /** Missing Drivers */
            missing_drivers: string[];
            /** Model Family */
            model_family: string;
            /** Model Version */
            model_version: string;
            /** Outcomes */
            outcomes: components["schemas"]["ContestantForecast"][];
            /** Provenance */
            provenance: components["schemas"]["SourceRef"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Regional Forecast Supported */
            regional_forecast_supported: boolean;
            /** Seed */
            seed: number;
            /** Selection Status */
            selection_status: string;
            /** Simulation Count */
            simulation_count: number;
            /** Turnout Median */
            turnout_median: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Dependencies */
            dependencies?: {
                [key: string]: string;
            };
            /** Status */
            status: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Version */
            version: string;
        };
        /** Jurisdiction */
        Jurisdiction: {
            /** Blocking Reasons */
            blocking_reasons?: string[];
            /** @default mechanics_blocked */
            coverage_status: components["schemas"]["CoverageStatus"];
            /** Eligibility */
            eligibility: string;
            /** Flag */
            flag: string;
            /**
             * Forecast Enabled
             * @default true
             */
            forecast_enabled: boolean;
            /** Id */
            id: string;
            /**
             * Is Exception
             * @default false
             */
            is_exception: boolean;
            /** Iso3 */
            iso3?: string | null;
            /** Name */
            name: string;
            /** Region */
            region: string;
        };
        /** MapLayer */
        MapLayer: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            data_quality: components["schemas"]["QualityGrade"];
            /** Election Id */
            election_id: string;
            /** Freshness */
            freshness: string;
            /** Geojson */
            geojson?: {
                [key: string]: unknown;
            } | null;
            /** Model Version */
            model_version: string;
            /** Provenance */
            provenance: components["schemas"]["SourceRef"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Reason */
            reason: string;
            /** Supported */
            supported: boolean;
        };
        /** ModelComparison */
        ModelComparison: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            data_quality: components["schemas"]["QualityGrade"];
            /** Dataset Sha256 */
            dataset_sha256?: string | null;
            /** Election Id */
            election_id: string;
            /** Evaluated Horizon Max Days */
            evaluated_horizon_max_days?: number | null;
            /** Evaluated Horizon Min Days */
            evaluated_horizon_min_days?: number | null;
            /** Evaluation Period End */
            evaluation_period_end?: string | null;
            /** Evaluation Period Start */
            evaluation_period_start?: string | null;
            /**
             * Fold Count
             * @default 0
             */
            fold_count: number;
            /** Freshness */
            freshness: string;
            /**
             * Held Out Election Count
             * @default 0
             */
            held_out_election_count: number;
            /** Historical Leader */
            historical_leader?: string | null;
            /** Leakage Check */
            leakage_check: boolean;
            /** Message */
            message: string;
            /** Metrics */
            metrics: components["schemas"]["BacktestMetrics"][];
            /** Model Version */
            model_version: string;
            /** Provenance */
            provenance: components["schemas"]["SourceRef"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Selection Rule */
            selection_rule: string;
            /**
             * Simulation Count Per Model Fold
             * @default 0
             */
            simulation_count_per_model_fold: number;
            /** Status */
            status: string;
            /** Target Horizon Days */
            target_horizon_days?: number | null;
            /**
             * Vintage Verified
             * @default false
             */
            vintage_verified: boolean;
            /** Winner */
            winner: string | null;
        };
        /** OfficialResults */
        OfficialResults: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            data_quality: components["schemas"]["QualityGrade"];
            /** Election Id */
            election_id: string;
            /** Feed Available */
            feed_available: boolean;
            /** Freshness */
            freshness: string;
            /** Model Version */
            model_version: string;
            /** Provenance */
            provenance: components["schemas"]["SourceRef"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Reporting Fraction */
            reporting_fraction: number;
            /** Results */
            results: {
                [key: string]: unknown;
            }[];
            /** Status */
            status: string;
        };
        /**
         * QualityGrade
         * @enum {string}
         */
        QualityGrade: "A" | "B" | "C" | "D";
        /** SimulationSummary */
        SimulationSummary: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            data_quality: components["schemas"]["QualityGrade"];
            /** Election Id */
            election_id: string;
            /** Freshness */
            freshness: string;
            /** Model Family */
            model_family: string;
            /** Model Version */
            model_version: string;
            /** Outcomes */
            outcomes: components["schemas"]["ContestantForecast"][];
            /** Provenance */
            provenance: components["schemas"]["SourceRef"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Seed */
            seed: number;
            /** Simulation Count */
            simulation_count: number;
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** SourceLedger */
        SourceLedger: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            data_quality: components["schemas"]["QualityGrade"];
            /** Election Id */
            election_id: string;
            /** Freshness */
            freshness: string;
            /** Model Version */
            model_version: string;
            /** Provenance */
            provenance: components["schemas"]["SourceRef"][];
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Sources */
            sources: components["schemas"]["SourceRef"][];
        };
        /** SourceRef */
        SourceRef: {
            /** Authority */
            authority: string;
            /** Label */
            label: string;
            /** License */
            license: string;
            /** License Url */
            license_url: string;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Source Id */
            source_id: string;
            /** Url */
            url: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    catalog_status_v1_catalog_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogStatus"];
                };
            };
        };
    };
    elections_v1_elections_get: {
        parameters: {
            query?: {
                jurisdiction?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Election"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    election_detail_v1_elections__election_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtests_v1_elections__election_id__backtests_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coalitions_v1_elections__election_id__coalitions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoalitionReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    drivers_v1_elections__election_id__drivers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_v1_elections__election_id__forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alternative_forecast_v1_elections__election_id__forecast_alternatives__model_family__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
                model_family: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_history_v1_elections__election_id__forecasts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSnapshot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    map_layers_v1_elections__election_id__map_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapLayer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mechanics_v1_elections__election_id__mechanics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectionMechanics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_comparison_v1_elections__election_id__model_comparison_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    official_results_v1_elections__election_id__official_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficialResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulation_summary_v1_elections__election_id__simulations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_v1_elections__election_id__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                election_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceLedger"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_snapshot_v1_forecast_snapshots__snapshot_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jurisdictions_v1_jurisdictions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jurisdiction"][];
                };
            };
        };
    };
    stream_v1_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
